{{- define "reloading.microservice.hpa" -}}
{{- $componentName := .componentName -}}
{{- $config := .config -}}
{{- $context := .context -}}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "reloading.fullname" $context }}-{{ $componentName }}
  namespace: {{ $context.Values.namespace }}
  labels:
    {{- include "reloading.microservice.labels" (dict "componentName" $componentName "context" $context) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "reloading.fullname" $context }}-{{ $componentName }}
  minReplicas: {{ $config.hpa.minReplicas }}
  maxReplicas: {{ $config.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $config.hpa.targetCPUUtilizationPercentage }}
{{- end }}
