{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.rbac.clusterScope }}
kind: ClusterRole
{{- else }}
kind: Role
{{- end }}
metadata:
  name: {{ include "reloading.fullname" . }}
  {{- if not .Values.rbac.clusterScope }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "reloading.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.rbac.clusterScope }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
metadata:
  name: {{ include "reloading.fullname" . }}
  {{- if not .Values.rbac.clusterScope }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "reloading.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if .Values.rbac.clusterScope }}
  kind: ClusterRole
  {{- else }}
  kind: Role
  {{- end }}
  name: {{ include "reloading.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "reloading.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
{{- end }}
