apiVersion: v2
name: spring-load-development
description: A Helm chart for Spring Load Development application with PostgreSQL, Keycloak, and Observability stack
type: application
version: 0.1.0-SNAPSHOT
appVersion: 0.1.0-SNAPSHOT
maintainers:
  - name: Zhubin Salehi
    email: zhoozhoo@yahoo.com

dependencies:
  - name: observability
    version: 0.1.0-SNAPSHOT
    condition: observability.enabled
  - name: keycloak
    version: 0.1.0-SNAPSHOT
    condition: keycloak.enabled
  - name: postgresql
    version: 0.1.0-SNAPSHOT
    condition: postgresql.enabled
  - name: reloading
    version: 0.1.0-SNAPSHOT
    condition: reloading.enabled
