apiVersion: v2
name: spring-load-development
description: A Helm chart for Spring Load Development application with PostgreSQL, Keycloak, and Observability stack
type: application
version: 0.1.0-SNAPSHOT
appVersion: 0.1.0-SNAPSHOT
maintainers:
  - name: Zhubin Salehi
    email: zhoozhoo@yahoo.com
