{{- if .Values.realm.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.realm.configMapName | default "keycloak-realm-config" }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  realm.json: {{ .Files.Get "files/realm.json" | quote }}
{{- end }}
