{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  KC_DB_PASSWORD: {{ .Values.postgresql.password | b64enc }}
  KC_BOOTSTRAP_ADMIN_USERNAME: {{ .Values.auth.adminUser | b64enc }}
  KC_BOOTSTRAP_ADMIN_PASSWORD: {{ .Values.auth.adminPassword | b64enc }}
{{- end }}
